// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.proiectus.fragen.data;

import de.proiectus.fragen.data.Fragen;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Fragen_Roo_Configurable {
    
    declare @type: Fragen: @Configurable;
    
}
