//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.13 at 09:15:24 PM CET 
//


package de.proiectus.jaxb.job;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{}HeaderType"/>
 *         &lt;element name="Data">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="JobPositionPosting" type="{}JobPositionPostingType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="DeleteEntry" type="{}DeleteEntryType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "data"
})
@XmlRootElement(name = "HRBAXMLJobPositionPosting")
public class HRBAXMLJobPositionPosting {

    @XmlElement(name = "Header", required = true)
    protected HeaderType header;
    @XmlElement(name = "Data", required = true)
    protected HRBAXMLJobPositionPosting.Data data;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link HeaderType }
     *     
     */
    public HeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderType }
     *     
     */
    public void setHeader(HeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link HRBAXMLJobPositionPosting.Data }
     *     
     */
    public HRBAXMLJobPositionPosting.Data getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link HRBAXMLJobPositionPosting.Data }
     *     
     */
    public void setData(HRBAXMLJobPositionPosting.Data value) {
        this.data = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="JobPositionPosting" type="{}JobPositionPostingType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="DeleteEntry" type="{}DeleteEntryType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "jobPositionPosting",
        "deleteEntry"
    })
    public static class Data {

        @XmlElement(name = "JobPositionPosting")
        protected List<JobPositionPostingType> jobPositionPosting;
        @XmlElement(name = "DeleteEntry")
        protected List<DeleteEntryType> deleteEntry;

        /**
         * Gets the value of the jobPositionPosting property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the jobPositionPosting property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getJobPositionPosting().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JobPositionPostingType }
         * 
         * 
         */
        public List<JobPositionPostingType> getJobPositionPosting() {
            if (jobPositionPosting == null) {
                jobPositionPosting = new ArrayList<JobPositionPostingType>();
            }
            return this.jobPositionPosting;
        }

        /**
         * Gets the value of the deleteEntry property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the deleteEntry property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDeleteEntry().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DeleteEntryType }
         * 
         * 
         */
        public List<DeleteEntryType> getDeleteEntry() {
            if (deleteEntry == null) {
                deleteEntry = new ArrayList<DeleteEntryType>();
            }
            return this.deleteEntry;
        }

    }

}
