//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.13 at 09:15:24 PM CET 
//


package de.proiectus.jaxb.job;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.proiectus.jaxb.job package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.proiectus.jaxb.job
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HRBAXMLJobPositionPosting }
     * 
     */
    public HRBAXMLJobPositionPosting createHRBAXMLJobPositionPosting() {
        return new HRBAXMLJobPositionPosting();
    }

    /**
     * Create an instance of {@link JobPositionPostingType }
     * 
     */
    public JobPositionPostingType createJobPositionPostingType() {
        return new JobPositionPostingType();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation }
     * 
     */
    public JobPositionPostingType.JobPositionInformation createJobPositionPostingTypeJobPositionInformation() {
        return new JobPositionPostingType.JobPositionInformation();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.JobPositionRequirements }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.JobPositionRequirements createJobPositionPostingTypeJobPositionInformationJobPositionRequirements() {
        return new JobPositionPostingType.JobPositionInformation.JobPositionRequirements();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired createJobPositionPostingTypeJobPositionInformationJobPositionRequirementsQualificationsRequired() {
        return new JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.Mobility }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.Mobility createJobPositionPostingTypeJobPositionInformationJobPositionRequirementsQualificationsRequiredMobility() {
        return new JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.Mobility();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.SkillQualifs }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.SkillQualifs createJobPositionPostingTypeJobPositionInformationJobPositionRequirementsQualificationsRequiredSkillQualifs() {
        return new JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.SkillQualifs();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.CertificationQualifs }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.CertificationQualifs createJobPositionPostingTypeJobPositionInformationJobPositionRequirementsQualificationsRequiredCertificationQualifs() {
        return new JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.CertificationQualifs();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.Licences }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.Licences createJobPositionPostingTypeJobPositionInformationJobPositionRequirementsQualificationsRequiredLicences() {
        return new JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.Licences();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.ProfessionalTrainingQualifs }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.ProfessionalTrainingQualifs createJobPositionPostingTypeJobPositionInformationJobPositionRequirementsQualificationsRequiredProfessionalTrainingQualifs() {
        return new JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.ProfessionalTrainingQualifs();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.ProfessionalTrainingQualifs.ProfessionalTraining }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.ProfessionalTrainingQualifs.ProfessionalTraining createJobPositionPostingTypeJobPositionInformationJobPositionRequirementsQualificationsRequiredProfessionalTrainingQualifsProfessionalTraining() {
        return new JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.ProfessionalTrainingQualifs.ProfessionalTraining();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.LanguageQualifs }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.LanguageQualifs createJobPositionPostingTypeJobPositionInformationJobPositionRequirementsQualificationsRequiredLanguageQualifs() {
        return new JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.LanguageQualifs();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.EducationQualifs }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.EducationQualifs createJobPositionPostingTypeJobPositionInformationJobPositionRequirementsQualificationsRequiredEducationQualifs() {
        return new JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.EducationQualifs();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.JobPositionDescription }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.JobPositionDescription createJobPositionPostingTypeJobPositionInformationJobPositionDescription() {
        return new JobPositionPostingType.JobPositionInformation.JobPositionDescription();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.JobPositionDescription.Classification }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.JobPositionDescription.Classification createJobPositionPostingTypeJobPositionInformationJobPositionDescriptionClassification() {
        return new JobPositionPostingType.JobPositionInformation.JobPositionDescription.Classification();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.JobPositionDescription.JobPositionLocation }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.JobPositionDescription.JobPositionLocation createJobPositionPostingTypeJobPositionInformationJobPositionDescriptionJobPositionLocation() {
        return new JobPositionPostingType.JobPositionInformation.JobPositionDescription.JobPositionLocation();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.PostDetail }
     * 
     */
    public JobPositionPostingType.PostDetail createJobPositionPostingTypePostDetail() {
        return new JobPositionPostingType.PostDetail();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.PostDetail.BAContact }
     * 
     */
    public JobPositionPostingType.PostDetail.BAContact createJobPositionPostingTypePostDetailBAContact() {
        return new JobPositionPostingType.PostDetail.BAContact();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.PostDetail.PostedBy }
     * 
     */
    public JobPositionPostingType.PostDetail.PostedBy createJobPositionPostingTypePostDetailPostedBy() {
        return new JobPositionPostingType.PostDetail.PostedBy();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.PostDetail.PostedBy.Contact }
     * 
     */
    public JobPositionPostingType.PostDetail.PostedBy.Contact createJobPositionPostingTypePostDetailPostedByContact() {
        return new JobPositionPostingType.PostDetail.PostedBy.Contact();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.HiringOrg }
     * 
     */
    public JobPositionPostingType.HiringOrg createJobPositionPostingTypeHiringOrg() {
        return new JobPositionPostingType.HiringOrg();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link HRBAXMLJobPositionPosting.Data }
     * 
     */
    public HRBAXMLJobPositionPosting.Data createHRBAXMLJobPositionPostingData() {
        return new HRBAXMLJobPositionPosting.Data();
    }

    /**
     * Create an instance of {@link TelecommuncationType }
     * 
     */
    public TelecommuncationType createTelecommuncationType() {
        return new TelecommuncationType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link DeleteEntryType }
     * 
     */
    public DeleteEntryType createDeleteEntryType() {
        return new DeleteEntryType();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.BAInternalInformation }
     * 
     */
    public JobPositionPostingType.BAInternalInformation createJobPositionPostingTypeBAInternalInformation() {
        return new JobPositionPostingType.BAInternalInformation();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.JobPositionTitle }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.JobPositionTitle createJobPositionPostingTypeJobPositionInformationJobPositionTitle() {
        return new JobPositionPostingType.JobPositionInformation.JobPositionTitle();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.AlternativeJobPositionTitle }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.AlternativeJobPositionTitle createJobPositionPostingTypeJobPositionInformationAlternativeJobPositionTitle() {
        return new JobPositionPostingType.JobPositionInformation.AlternativeJobPositionTitle();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.ManagementQualifs }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.ManagementQualifs createJobPositionPostingTypeJobPositionInformationJobPositionRequirementsQualificationsRequiredManagementQualifs() {
        return new JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.ManagementQualifs();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.Mobility.DrivingLicence }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.Mobility.DrivingLicence createJobPositionPostingTypeJobPositionInformationJobPositionRequirementsQualificationsRequiredMobilityDrivingLicence() {
        return new JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.Mobility.DrivingLicence();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.Mobility.Vehicle }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.Mobility.Vehicle createJobPositionPostingTypeJobPositionInformationJobPositionRequirementsQualificationsRequiredMobilityVehicle() {
        return new JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.Mobility.Vehicle();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.SkillQualifs.HardSkill }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.SkillQualifs.HardSkill createJobPositionPostingTypeJobPositionInformationJobPositionRequirementsQualificationsRequiredSkillQualifsHardSkill() {
        return new JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.SkillQualifs.HardSkill();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.SkillQualifs.SoftSkill }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.SkillQualifs.SoftSkill createJobPositionPostingTypeJobPositionInformationJobPositionRequirementsQualificationsRequiredSkillQualifsSoftSkill() {
        return new JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.SkillQualifs.SoftSkill();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.CertificationQualifs.Certification }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.CertificationQualifs.Certification createJobPositionPostingTypeJobPositionInformationJobPositionRequirementsQualificationsRequiredCertificationQualifsCertification() {
        return new JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.CertificationQualifs.Certification();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.Licences.Licence }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.Licences.Licence createJobPositionPostingTypeJobPositionInformationJobPositionRequirementsQualificationsRequiredLicencesLicence() {
        return new JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.Licences.Licence();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.ProfessionalTrainingQualifs.ProfessionalTraining.Title }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.ProfessionalTrainingQualifs.ProfessionalTraining.Title createJobPositionPostingTypeJobPositionInformationJobPositionRequirementsQualificationsRequiredProfessionalTrainingQualifsProfessionalTrainingTitle() {
        return new JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.ProfessionalTrainingQualifs.ProfessionalTraining.Title();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.LanguageQualifs.Language }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.LanguageQualifs.Language createJobPositionPostingTypeJobPositionInformationJobPositionRequirementsQualificationsRequiredLanguageQualifsLanguage() {
        return new JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.LanguageQualifs.Language();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.EducationQualifs.School }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.EducationQualifs.School createJobPositionPostingTypeJobPositionInformationJobPositionRequirementsQualificationsRequiredEducationQualifsSchool() {
        return new JobPositionPostingType.JobPositionInformation.JobPositionRequirements.QualificationsRequired.EducationQualifs.School();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.JobPositionDescription.Application }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.JobPositionDescription.Application createJobPositionPostingTypeJobPositionInformationJobPositionDescriptionApplication() {
        return new JobPositionPostingType.JobPositionInformation.JobPositionDescription.Application();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.JobPositionDescription.CompensationDescription }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.JobPositionDescription.CompensationDescription createJobPositionPostingTypeJobPositionInformationJobPositionDescriptionCompensationDescription() {
        return new JobPositionPostingType.JobPositionInformation.JobPositionDescription.CompensationDescription();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.JobPositionDescription.Classification.Schedule }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.JobPositionDescription.Classification.Schedule createJobPositionPostingTypeJobPositionInformationJobPositionDescriptionClassificationSchedule() {
        return new JobPositionPostingType.JobPositionInformation.JobPositionDescription.Classification.Schedule();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.JobPositionDescription.Classification.Duration }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.JobPositionDescription.Classification.Duration createJobPositionPostingTypeJobPositionInformationJobPositionDescriptionClassificationDuration() {
        return new JobPositionPostingType.JobPositionInformation.JobPositionDescription.Classification.Duration();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.JobPositionInformation.JobPositionDescription.JobPositionLocation.Location }
     * 
     */
    public JobPositionPostingType.JobPositionInformation.JobPositionDescription.JobPositionLocation.Location createJobPositionPostingTypeJobPositionInformationJobPositionDescriptionJobPositionLocationLocation() {
        return new JobPositionPostingType.JobPositionInformation.JobPositionDescription.JobPositionLocation.Location();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.PostDetail.BAContact.PostalAddress }
     * 
     */
    public JobPositionPostingType.PostDetail.BAContact.PostalAddress createJobPositionPostingTypePostDetailBAContactPostalAddress() {
        return new JobPositionPostingType.PostDetail.BAContact.PostalAddress();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.PostDetail.PostedBy.Contact.InterviewContact }
     * 
     */
    public JobPositionPostingType.PostDetail.PostedBy.Contact.InterviewContact createJobPositionPostingTypePostDetailPostedByContactInterviewContact() {
        return new JobPositionPostingType.PostDetail.PostedBy.Contact.InterviewContact();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.PostDetail.PostedBy.Contact.InterviewLocation }
     * 
     */
    public JobPositionPostingType.PostDetail.PostedBy.Contact.InterviewLocation createJobPositionPostingTypePostDetailPostedByContactInterviewLocation() {
        return new JobPositionPostingType.PostDetail.PostedBy.Contact.InterviewLocation();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.PostDetail.PostedBy.Contact.Interview }
     * 
     */
    public JobPositionPostingType.PostDetail.PostedBy.Contact.Interview createJobPositionPostingTypePostDetailPostedByContactInterview() {
        return new JobPositionPostingType.PostDetail.PostedBy.Contact.Interview();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.HiringOrg.Industry }
     * 
     */
    public JobPositionPostingType.HiringOrg.Industry createJobPositionPostingTypeHiringOrgIndustry() {
        return new JobPositionPostingType.HiringOrg.Industry();
    }

    /**
     * Create an instance of {@link JobPositionPostingType.HiringOrg.Contact }
     * 
     */
    public JobPositionPostingType.HiringOrg.Contact createJobPositionPostingTypeHiringOrgContact() {
        return new JobPositionPostingType.HiringOrg.Contact();
    }

}
