package de.proiectus.job.gui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.VaadinSession;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button.ClickEvent;

public class Maske2 extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private TabSheet tabSheet_1;
	@AutoGenerated
	private GridLayout gridLayout_1;
	@AutoGenerated
	private Button button_1;
	@AutoGenerated
	private PopupDateField popupDateField_1;
	@AutoGenerated
	private TextField textField_2;
	@AutoGenerated
	private Label label_3;
	@AutoGenerated
	private GridLayout gridLayout_2;
	@AutoGenerated
	private Label label_4;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Maske2() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// tabSheet_1
		tabSheet_1 = buildTabSheet_1();
		mainLayout.addComponent(tabSheet_1,
				"top:60.0px;bottom:102.0px;left:40.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private TabSheet buildTabSheet_1() {
		// common part: create layout
		tabSheet_1 = new TabSheet();
		tabSheet_1.setStyleName("Tab1");
		tabSheet_1.setCaption("Tab1");
		tabSheet_1.setImmediate(true);
		tabSheet_1.setWidth("100.0%");
		tabSheet_1.setHeight("100.0%");
		
		// gridLayout_2
		gridLayout_2 = buildGridLayout_2();
		tabSheet_1.addTab(gridLayout_2, "Tab2Grid", null);
		
		// gridLayout_1
		gridLayout_1 = buildGridLayout_1();
		tabSheet_1.addTab(gridLayout_1, "Tab1Grid", null);
		
		return tabSheet_1;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_2() {
		// common part: create layout
		gridLayout_2 = new GridLayout();
		gridLayout_2.setStyleName("Tab2Gridn");
		gridLayout_2.setCaption("Tab2Grid");
		gridLayout_2.setImmediate(false);
		gridLayout_2.setWidth("100.0%");
		gridLayout_2.setHeight("100.0%");
		gridLayout_2.setMargin(false);
		gridLayout_2.setColumns(6);
		gridLayout_2.setRows(6);
		
		// label_4
		label_4 = new Label();
		label_4.setImmediate(false);
		label_4.setWidth("-1px");
		label_4.setHeight("-1px");
		label_4.setValue("Label");
		gridLayout_2.addComponent(label_4, 2, 2);
		
		Button button = new Button("Click Me!");
		button.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				VaadinSession.getCurrent().setAttribute("datum", "hslll");// popupDateField_1.getData());
				mainLayout.getUI().setContent(new Maske3());
			}
		});
		gridLayout_2.addComponent(button);
		
		return gridLayout_2;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_1() {
		// common part: create layout
		gridLayout_1 = new GridLayout();
		gridLayout_1.setStyleName("Tab1Gridn");
		gridLayout_1.setCaption("Tab1Grid");
		gridLayout_1.setImmediate(false);
		gridLayout_1.setWidth("100.0%");
		gridLayout_1.setHeight("100.0%");
		gridLayout_1.setMargin(false);
		gridLayout_1.setColumns(6);
		gridLayout_1.setRows(6);
		
		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("219px");
		label_3.setHeight("18px");
		label_3.setValue("Label");
		gridLayout_1.addComponent(label_3, 0, 0);
		
		// textField_2
		textField_2 = new TextField();
		textField_2.setImmediate(false);
		textField_2.setWidth("-1px");
		textField_2.setHeight("-1px");
		gridLayout_1.addComponent(textField_2, 0, 1);
		
		// popupDateField_1
		popupDateField_1 = new PopupDateField();
		popupDateField_1.setImmediate(false);
		popupDateField_1.setWidth("-1px");
		popupDateField_1.setHeight("-1px");
		gridLayout_1.addComponent(popupDateField_1, 2, 1);
		
		// button_1
		button_1 = new Button();
		button_1.setCaption("Button");
		button_1.setImmediate(true);
		button_1.setWidth("-1px");
		button_1.setHeight("-1px");
		gridLayout_1.addComponent(button_1, 0, 4);
		
		return gridLayout_1;
	}

}
