INSERT INTO hiring_org_size (id, bezeichnung, nummer,version) VALUES(1,'weniger als 6',1,1);
INSERT INTO hiring_org_size (id, bezeichnung, nummer,version) VALUES(2,'zwischen 6 und 50',2,1);
INSERT INTO hiring_org_size (id, bezeichnung, nummer,version) VALUES(3,'zwischen 51 und 500',3,1);
INSERT INTO hiring_org_size (id, bezeichnung, nummer,version) VALUES(4,'zwischen 501 und 5000',4,1);
INSERT INTO hiring_org_size (id, bezeichnung, nummer,version) VALUES(5,'zwischen 5001 und 50000',5,1);
INSERT INTO hiring_org_size (id, bezeichnung, nummer,version) VALUES(6,'mehr als 50000',6,1);
INSERT INTO n_a_i_c_s (id, bezeichnung, nummer,version) VALUES(7,'Moegliche Werte sind dem zu Grunde liegenden Katalog zu entnehmen ',0,1);
INSERT INTO salutation (id, bezeichnung, nummer,version) VALUES(8,'Herr',1,1);
INSERT INTO salutation (id, bezeichnung, nummer,version) VALUES(9,'Frau',2,1);
INSERT INTO status (id, bezeichnung, nummer,version) VALUES(10,'veroeffentlicht',1,1);
INSERT INTO status (id, bezeichnung, nummer,version) VALUES(11,'anonym veroeffentlicht',2,1);
INSERT INTO status (id, bezeichnung, nummer,version) VALUES(12,'nicht veroeffentlicht',3,1);
INSERT INTO status (id, bezeichnung, nummer,version) VALUES(13,'intern veroeffentlicht',6,1);
INSERT INTO status (id, bezeichnung, nummer,version) VALUES(14,'intern anonym veroeffentlicht',7,1);
INSERT INTO status (id, bezeichnung, nummer,version) VALUES(15,'intern und Jobboerse anonym veroeffentlicht',8,1);
INSERT INTO aktion (id, bezeichnung, nummer,version) VALUES(16,'Neuanlage',1,1);
INSERT INTO aktion (id, bezeichnung, nummer,version) VALUES(17,'Aktualisierung',2,1);
INSERT INTO aktion (id, bezeichnung, nummer,version) VALUES(18,'Loeschung',3,1);
INSERT INTO supplier_industrie (id, bezeichnung, nummer,version) VALUES(19,'Allgemeine Stellenboersen ',1,1);
INSERT INTO supplier_industrie (id, bezeichnung, nummer,version) VALUES(20,'Regionale Stellenboersen ',2,1);
INSERT INTO supplier_industrie (id, bezeichnung, nummer,version) VALUES(21,'Berufs- und branchenspez. Stellenboersen ',3,1);
INSERT INTO supplier_industrie (id, bezeichnung, nummer,version) VALUES(22,'Sonstige spezielle Stellenboersen ',4,1);
INSERT INTO supplier_industrie (id, bezeichnung, nummer,version) VALUES(23,'Arbeitgeber',5,1);
INSERT INTO salutation (id, bezeichnung, nummer,version) VALUES(24,'Herr ',1,1);
INSERT INTO salutation (id, bezeichnung, nummer,version) VALUES(25,'Frau ',2,1);
INSERT INTO salutation (id, bezeichnung, nummer,version) VALUES(26,'Herr',1,1);
INSERT INTO salutation (id, bezeichnung, nummer,version) VALUES(27,'Frau',2,1);
INSERT INTO country_code (id, bezeichnung, nummer,version) VALUES(28,'ISO 3166-1',0,1);
INSERT INTO country_code (id, bezeichnung, nummer,version) VALUES(29,'alpha-2 Klassifizierung',0,1);
INSERT INTO region (id, bezeichnung, nummer,version) VALUES(30,'zu entnehmen aus der Datei Regionen-VAM-Code die im Outverzeichnis der Software Connect:Direct des jeweiligen Kooperationspartners zur Verfuegung gestellt wird. Falls dort nicht enthalten: Sonstiges ',17,1);
INSERT INTO b_a_supervision (id, bezeichnung, nummer,version) VALUES(31,'ja',1,1);
INSERT INTO b_a_supervision (id, bezeichnung, nummer,version) VALUES(32,'nein',0,1);
INSERT INTO supervision_desired (id, bezeichnung, nummer,version) VALUES(33,'ja',1,1);
INSERT INTO supervision_desired (id, bezeichnung, nummer,version) VALUES(34,'nein',0,1);
INSERT INTO salutation (id, bezeichnung, nummer,version) VALUES(35,'Herr',1,1);
INSERT INTO salutation (id, bezeichnung, nummer,version) VALUES(36,'Frau',2,1);
INSERT INTO country_code (id, bezeichnung, nummer,version) VALUES(37,'ISO 3166-1',0,1);
INSERT INTO country_code (id, bezeichnung, nummer,version) VALUES(38,'alpha-2 Klassifizierung',0,1);
INSERT INTO region (id, bezeichnung, nummer,version) VALUES(39,'zu entnehmen aus der Datei Regionen-VAM-Code die im Outverzeichnis der Software Connect:Direct des jeweiligen Kooperationspartners zur Verfuegung gestellt wird. Falls dort nicht enthalten: Sonstiges ',17,1);
INSERT INTO title_code (id, bezeichnung, nummer,version) VALUES(40,'gemaess DKZ ',0,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(41,'Nicht relevant',1,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(42,'Bachelor (BA)',2,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(43,'Bachelor (FH)',3,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(44,'Bachelor (Uni)',4,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(45,'Diplom (BA)',5,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(46,'Diplom (FH)',6,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(47,'Diplom (Uni)',7,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(48,'Kirchliches Examen / Lizenziat',8,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(49,'Magister',9,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(50,'Master (FH)',10,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(51,'Master (Uni)',11,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(52,'Promotion',12,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(53,'Staatsexamen',13,1);
INSERT INTO title_code (id, bezeichnung, nummer,version) VALUES(54,'gemaess DKZ ',0,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(55,'Nicht relevant',1,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(56,'Bachelor (BA)',2,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(57,'Bachelor (FH)',3,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(58,'Bachelor (Uni)',4,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(59,'Diplom (BA)',5,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(60,'Diplom (FH)',6,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(61,'Diplom (Uni)',7,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(62,'Kirchliches Examen / Lizenziat',8,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(63,'Magister',9,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(64,'Master (FH)',10,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(65,'Master (Uni)',11,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(66,'Promotion',12,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(67,'Staatsexamen',13,1);
INSERT INTO job_offer_type (id, bezeichnung, nummer,version) VALUES(68,'Arbeitsplatz ',1,1);
INSERT INTO job_offer_type (id, bezeichnung, nummer,version) VALUES(69,'Selbstaendigkeit ',2,1);
INSERT INTO job_offer_type (id, bezeichnung, nummer,version) VALUES(70,'Ausbildungsplatz ',4,1);
INSERT INTO job_offer_type (id, bezeichnung, nummer,version) VALUES(71,'Praktikum/Traineestelle',34,1);
INSERT INTO job_offer_type (id, bezeichnung, nummer,version) VALUES(72,'Fachkraft',36,1);
INSERT INTO job_offer_type (id, bezeichnung, nummer,version) VALUES(73,'Fuehrungskraft',37,1);
INSERT INTO job_offer_type (id, bezeichnung, nummer,version) VALUES(74,'Helfer',38,1);
INSERT INTO job_offer_type (id, bezeichnung, nummer,version) VALUES(75,'Kuenstler',40,1);
INSERT INTO special_engagement (id, bezeichnung, nummer,version) VALUES(76,'Gastarbeitnehmer',1,1);
INSERT INTO special_engagement (id, bezeichnung, nummer,version) VALUES(77,'Haushaltshilfe',2,1);
INSERT INTO special_engagement (id, bezeichnung, nummer,version) VALUES(78,'Private Arbeitsvermittlung',3,1);
INSERT INTO social_insurance (id, bezeichnung, nummer,version) VALUES(79,'ja',1,1);
INSERT INTO social_insurance (id, bezeichnung, nummer,version) VALUES(80,'nein',0,1);
INSERT INTO education_authorisation (id, bezeichnung, nummer,version) VALUES(81,'ja',1,1);
INSERT INTO education_authorisation (id, bezeichnung, nummer,version) VALUES(82,'nein',0,1);
INSERT INTO country_code (id, bezeichnung, nummer,version) VALUES(83,'ISO 3166-1',0,1);
INSERT INTO country_code (id, bezeichnung, nummer,version) VALUES(84,'alpha-2 Klassifizierung',0,1);
INSERT INTO region (id, bezeichnung, nummer,version) VALUES(85,'zu entnehmen aus der Datei Regionen-VAM-Code die im Outverzeichnis der Software Connect:Direct des jeweiligen Kooperationspartners zur Verfuegung gestellt wird. Falls dort nicht enthalten: Sonstiges ',17,1);
INSERT INTO kind_of_application (id, bezeichnung, nummer,version) VALUES(86,'telefonisch',1,1);
INSERT INTO kind_of_application (id, bezeichnung, nummer,version) VALUES(87,'schriftlich',2,1);
INSERT INTO kind_of_application (id, bezeichnung, nummer,version) VALUES(88,'per E-Mail',3,1);
INSERT INTO kind_of_application (id, bezeichnung, nummer,version) VALUES(89,'persoenlich',4,1);
INSERT INTO kind_of_application (id, bezeichnung, nummer,version) VALUES(90,'mit firmeneigenen Unterlagen',5,1);
INSERT INTO kind_of_application (id, bezeichnung, nummer,version) VALUES(91,'ueber Internet',6,1);
INSERT INTO kind_of_application (id, bezeichnung, nummer,version) VALUES(92,'ueber www.arbeitsagentur.de',8,1);
INSERT INTO leadership (id, bezeichnung, nummer,version) VALUES(93,'Keine Führungsverantwortung ',1,1);
INSERT INTO leadership (id, bezeichnung, nummer,version) VALUES(94,'Alle Führungsebenen ',2,1);
INSERT INTO leadership (id, bezeichnung, nummer,version) VALUES(95,'Teamleitung',0,1);
INSERT INTO leadership (id, bezeichnung, nummer,version) VALUES(96,'Projektleitung',0,1);
INSERT INTO leadership (id, bezeichnung, nummer,version) VALUES(97,'Gruppenleitung ',3,1);
INSERT INTO leadership (id, bezeichnung, nummer,version) VALUES(98,'Abteilungsleitung',0,1);
INSERT INTO leadership (id, bezeichnung, nummer,version) VALUES(99,'Bereichsleitung',0,1);
INSERT INTO leadership (id, bezeichnung, nummer,version) VALUES(100,'Ressortleitung ',4,1);
INSERT INTO leadership (id, bezeichnung, nummer,version) VALUES(101,'Geschäftsleitung',0,1);
INSERT INTO leadership (id, bezeichnung, nummer,version) VALUES(102,'Vorstand',0,1);
INSERT INTO leadership (id, bezeichnung, nummer,version) VALUES(103,'Betriebsleitung ',5,1);
INSERT INTO leadership (id, bezeichnung, nummer,version) VALUES(104,'Stabsfunktion ',6,1);
INSERT INTO mini_job (id, bezeichnung, nummer,version) VALUES(105,'ja ',1,1);
INSERT INTO mini_job (id, bezeichnung, nummer,version) VALUES(106,'nein ',0,1);
INSERT INTO working_plan (id, bezeichnung, nummer,version) VALUES(107,'Vollzeit',1,1);
INSERT INTO working_plan (id, bezeichnung, nummer,version) VALUES(108,'Teilzeit - Schicht',3,1);
INSERT INTO working_plan (id, bezeichnung, nummer,version) VALUES(109,'Wochenende',4,1);
INSERT INTO working_plan (id, bezeichnung, nummer,version) VALUES(110,'Nachtarbeit',5,1);
INSERT INTO working_plan (id, bezeichnung, nummer,version) VALUES(111,'Teilzeit - Vormittag',7,1);
INSERT INTO working_plan (id, bezeichnung, nummer,version) VALUES(112,'Teilzeit - Nachmittag',8,1);
INSERT INTO working_plan (id, bezeichnung, nummer,version) VALUES(113,'Teilzeit - Abend',9,1);
INSERT INTO working_plan (id, bezeichnung, nummer,version) VALUES(114,'Teilzeit - flexibel',10,1);
INSERT INTO working_plan (id, bezeichnung, nummer,version) VALUES(115,'Heimarbeit',11,1);
INSERT INTO working_plan (id, bezeichnung, nummer,version) VALUES(116,'Schicht',12,1);
INSERT INTO temporary_or_regular (id, bezeichnung, nummer,version) VALUES(117,'befristet ',1,1);
INSERT INTO temporary_or_regular (id, bezeichnung, nummer,version) VALUES(118,'unbefristet ',2,1);
INSERT INTO temporary_or_regular (id, bezeichnung, nummer,version) VALUES(119,'alle ',3,1);
INSERT INTO take_over (id, bezeichnung, nummer,version) VALUES(120,'ja ',1,1);
INSERT INTO take_over (id, bezeichnung, nummer,version) VALUES(121,'nein ',0,1);
INSERT INTO daily_rate (id, bezeichnung, nummer,version) VALUES(122,'kleiner 50 ',1,1);
INSERT INTO daily_rate (id, bezeichnung, nummer,version) VALUES(123,'50 - 200 ',2,1);
INSERT INTO daily_rate (id, bezeichnung, nummer,version) VALUES(124,'200 - 300 ',3,1);
INSERT INTO daily_rate (id, bezeichnung, nummer,version) VALUES(125,'300 - 500 ',4,1);
INSERT INTO daily_rate (id, bezeichnung, nummer,version) VALUES(126,'500 - 750 ',5,1);
INSERT INTO daily_rate (id, bezeichnung, nummer,version) VALUES(127,'750 - 1000 ',6,1);
INSERT INTO daily_rate (id, bezeichnung, nummer,version) VALUES(128,'1000 - 1500 ',7,1);
INSERT INTO daily_rate (id, bezeichnung, nummer,version) VALUES(129,'1500 - 2000 ',8,1);
INSERT INTO daily_rate (id, bezeichnung, nummer,version) VALUES(130,'2000 - 3000 ',9,1);
INSERT INTO daily_rate (id, bezeichnung, nummer,version) VALUES(131,'3000 - 4000 ',10,1);
INSERT INTO daily_rate (id, bezeichnung, nummer,version) VALUES(132,'4000 - 5000 ',11,1);
INSERT INTO daily_rate (id, bezeichnung, nummer,version) VALUES(133,'5000 - 6000 ',12,1);
INSERT INTO daily_rate (id, bezeichnung, nummer,version) VALUES(134,'6000 - 7000 ',13,1);
INSERT INTO daily_rate (id, bezeichnung, nummer,version) VALUES(135,'7000 - 8000 ',14,1);
INSERT INTO daily_rate (id, bezeichnung, nummer,version) VALUES(136,'8000 - 9000 ',15,1);
INSERT INTO daily_rate (id, bezeichnung, nummer,version) VALUES(137,'9000 - 10000 ',16,1);
INSERT INTO daily_rate (id, bezeichnung, nummer,version) VALUES(138,'grösser 10000 ',17,1);
INSERT INTO employer_payscale_bound (id, bezeichnung, nummer,version) VALUES(139,'ja',1,1);
INSERT INTO employer_payscale_bound (id, bezeichnung, nummer,version) VALUES(140,'nein',0,1);
INSERT INTO housing (id, bezeichnung, nummer,version) VALUES(141,'ja ',1,1);
INSERT INTO housing (id, bezeichnung, nummer,version) VALUES(142,'nein ',0,1);
INSERT INTO edu_degree (id, bezeichnung, nummer,version) VALUES(143,'kein Schulabschluss ',1,1);
INSERT INTO edu_degree (id, bezeichnung, nummer,version) VALUES(144,'Hauptschulabschluss ',2,1);
INSERT INTO edu_degree (id, bezeichnung, nummer,version) VALUES(145,'Mittlere Reife / Mittlerer Bildungsabschluss ',3,1);
INSERT INTO edu_degree (id, bezeichnung, nummer,version) VALUES(146,'Fachhochschulreife (einschl. nur theoret. Teil) ',4,1);
INSERT INTO edu_degree (id, bezeichnung, nummer,version) VALUES(147,'Fachabitur / Fachgebundene Hochschulreife ',5,1);
INSERT INTO edu_degree (id, bezeichnung, nummer,version) VALUES(148,'Abitur / Allgemeine Hochschulreife ',6,1);
INSERT INTO edu_degree (id, bezeichnung, nummer,version) VALUES(149,'Abschluss Fachhochschule (oder Vergl.) ',7,1);
INSERT INTO edu_degree (id, bezeichnung, nummer,version) VALUES(150,'Wissenschaftliche Hochschule / Universitaet ',9,1);
INSERT INTO edu_degree (id, bezeichnung, nummer,version) VALUES(151,'Abschluss der Foerderschule ',11,1);
INSERT INTO edu_degree (id, bezeichnung, nummer,version) VALUES(152,'Qualifizierender / erweiterter Haupschulabschluss ',12,1);
INSERT INTO edu_degree (id, bezeichnung, nummer,version) VALUES(153,'Abgaenger Klasse 11 -13 ohne Abschluss ',13,1);
INSERT INTO edu_degree (id, bezeichnung, nummer,version) VALUES(154,'Hochschule ohne Abschluss ',14,1);
INSERT INTO edu_degree (id, bezeichnung, nummer,version) VALUES(155,'nicht relevant ',15,1);
INSERT INTO leadership_type (id, bezeichnung, nummer,version) VALUES(156,'Technische Leitung ',1,1);
INSERT INTO leadership_type (id, bezeichnung, nummer,version) VALUES(157,'Kaufmännische Leitung ',2,1);
INSERT INTO leadership_type (id, bezeichnung, nummer,version) VALUES(158,'Technische und kaufmännische Leitung ',3,1);
INSERT INTO authority (id, bezeichnung, nummer,version) VALUES(159,'Handlungsvollmacht ',1,1);
INSERT INTO authority (id, bezeichnung, nummer,version) VALUES(160,'Prokura ',2,1);
INSERT INTO authority (id, bezeichnung, nummer,version) VALUES(161,'Generalvollmacht ',3,1);
INSERT INTO leadership_ex (id, bezeichnung, nummer,version) VALUES(162,'bis 2 Jahre ',1,1);
INSERT INTO leadership_ex (id, bezeichnung, nummer,version) VALUES(163,'2 bis 5 Jahre ',2,1);
INSERT INTO leadership_ex (id, bezeichnung, nummer,version) VALUES(164,'mehr als 5 Jahre ',3,1);
INSERT INTO budget_resp (id, bezeichnung, nummer,version) VALUES(165,'bis 1 Mio. EUR p.a. ',1,1);
INSERT INTO budget_resp (id, bezeichnung, nummer,version) VALUES(166,'1 – 9 Mio. EUR p.a. ',2,1);
INSERT INTO budget_resp (id, bezeichnung, nummer,version) VALUES(167,'10 – 49 Mio. EUR p.a. ',3,1);
INSERT INTO budget_resp (id, bezeichnung, nummer,version) VALUES(168,'ab 50 Mio. EUR p.a. ',4,1);
INSERT INTO employee_resp (id, bezeichnung, nummer,version) VALUES(169,'bis 9 Mitarbeiter/innen ',1,1);
INSERT INTO employee_resp (id, bezeichnung, nummer,version) VALUES(170,'10 – 49 Mitarbeiter/innen ',2,1);
INSERT INTO employee_resp (id, bezeichnung, nummer,version) VALUES(171,'50 – 499 Mitarbeiter/innen ',3,1);
INSERT INTO employee_resp (id, bezeichnung, nummer,version) VALUES(172,'500 und mehr Mitarbeiter/innen ',4,1);
INSERT INTO language_name (id, bezeichnung, nummer,version) VALUES(173,'siehe Kompetenzkatalog',0,1);
INSERT INTO language_name (id, bezeichnung, nummer,version) VALUES(174,'Sektion Sprachen',0,1);
INSERT INTO language_level (id, bezeichnung, nummer,version) VALUES(175,'Nicht erforderlich ',0,1);
INSERT INTO language_level (id, bezeichnung, nummer,version) VALUES(176,'Grundkenntnisse ',1,1);
INSERT INTO language_level (id, bezeichnung, nummer,version) VALUES(177,'Erweiterte Kenntnisse ',2,1);
INSERT INTO language_level (id, bezeichnung, nummer,version) VALUES(178,'Verhandlungssicher ',3,1);
INSERT INTO language_level (id, bezeichnung, nummer,version) VALUES(179,'Zwingend erforderlich ',4,1);
INSERT INTO title_code (id, bezeichnung, nummer,version) VALUES(180,'gemaess DKZ ',0,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(181,'Nicht relevant',1,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(182,'Bachelor (BA)',2,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(183,'Bachelor (FH)',3,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(184,'Bachelor (Uni)',4,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(185,'Diplom (BA)',5,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(186,'Diplom (FH)',6,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(187,'Diplom (Uni)',7,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(188,'Kirchliches Examen / Lizenziat',8,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(189,'Magister',9,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(190,'Master (FH)',10,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(191,'Master (Uni)',11,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(192,'Promotion',12,1);
INSERT INTO degree (id, bezeichnung, nummer,version) VALUES(193,'Staatsexamen',13,1);
INSERT INTO licence_name (id, bezeichnung, nummer,version) VALUES(194,'siehe Kompetenzkatalog',0,1);
INSERT INTO licence_name (id, bezeichnung, nummer,version) VALUES(195,'Sektion Lizenzen',0,1);
INSERT INTO licence_level (id, bezeichnung, nummer,version) VALUES(196,'Wünschenswert ',1,1);
INSERT INTO licence_level (id, bezeichnung, nummer,version) VALUES(197,'Zwingend erforderlich ',2,1);
INSERT INTO skill_name (id, bezeichnung, nummer,version) VALUES(198,'gemaess Kompetenzkataloge die im Outverzeichnis der Software Connect:Direct des jeweiligen Kooperationspartners zur Verfuegung gestellt werden',0,1);
INSERT INTO skill_level (id, bezeichnung, nummer,version) VALUES(199,'Grundkenntnisse ',1,1);
INSERT INTO skill_level (id, bezeichnung, nummer,version) VALUES(200,'Erweiterte Kenntnisse ',2,1);
INSERT INTO skill_level (id, bezeichnung, nummer,version) VALUES(201,'Expertenkenntnisse (3); Zwingend erforderlich ',4,1);
INSERT INTO skill_name (id, bezeichnung, nummer,version) VALUES(202,'Analyse- und Problemlösefähigkeit ',1,1);
INSERT INTO skill_name (id, bezeichnung, nummer,version) VALUES(203,'Auffassungsfähigkeit/-gabe ',2,1);
INSERT INTO skill_name (id, bezeichnung, nummer,version) VALUES(204,'Entscheidungsfähigkeit ',3,1);
INSERT INTO skill_name (id, bezeichnung, nummer,version) VALUES(205,'Ganzheitliches Denken ',4,1);
INSERT INTO skill_name (id, bezeichnung, nummer,version) VALUES(206,'Organisationsfähigkeit ',5,1);
INSERT INTO skill_name (id, bezeichnung, nummer,version) VALUES(207,'Belastbarkeit ',6,1);
INSERT INTO skill_name (id, bezeichnung, nummer,version) VALUES(208,'Eigeninitiative ',7,1);
INSERT INTO skill_name (id, bezeichnung, nummer,version) VALUES(209,'Motivation/ Leistungsbereitschaft ',8,1);
INSERT INTO skill_name (id, bezeichnung, nummer,version) VALUES(210,'Selbständiges Arbeiten ',9,1);
INSERT INTO skill_name (id, bezeichnung, nummer,version) VALUES(211,'Zielstrebigkeit/Ergebnisorientierung ',10,1);
INSERT INTO skill_name (id, bezeichnung, nummer,version) VALUES(212,'Einfühlungsvermögen ',11,1);
INSERT INTO skill_name (id, bezeichnung, nummer,version) VALUES(213,'Führungsfähigkeit ',12,1);
INSERT INTO skill_name (id, bezeichnung, nummer,version) VALUES(214,'Kommunikationsfähigkeit ',13,1);
INSERT INTO skill_name (id, bezeichnung, nummer,version) VALUES(215,'Kundenorientierung ',14,1);
INSERT INTO skill_name (id, bezeichnung, nummer,version) VALUES(216,'Teamfähigkeit ',15,1);
INSERT INTO skill_name (id, bezeichnung, nummer,version) VALUES(217,'Flexibilität ',16,1);
INSERT INTO skill_name (id, bezeichnung, nummer,version) VALUES(218,'Kreativität ',17,1);
INSERT INTO skill_name (id, bezeichnung, nummer,version) VALUES(219,'Lernbereitschaft ',18,1);
INSERT INTO skill_name (id, bezeichnung, nummer,version) VALUES(220,'Sorgfalt/Genauigkeit ',19,1);
INSERT INTO skill_name (id, bezeichnung, nummer,version) VALUES(221,'Zuverlässigkeit ',20,1);
INSERT INTO driving_licence_name (id, bezeichnung, nummer,version) VALUES(222,'siehe Kompetenzkatalog',0,1);
INSERT INTO driving_licence_name (id, bezeichnung, nummer,version) VALUES(223,'Sektion Fuehrerscheine',0,1);
INSERT INTO driving_licence_required (id, bezeichnung, nummer,version) VALUES(224,'Wünschenswert ',1,1);
INSERT INTO driving_licence_required (id, bezeichnung, nummer,version) VALUES(225,'Zwingend erforderlich ',2,1);
INSERT INTO car (id, bezeichnung, nummer,version) VALUES(226,'nicht gefordert ',0,1);
INSERT INTO car (id, bezeichnung, nummer,version) VALUES(227,'gefordert ',1,1);
INSERT INTO motorcycle (id, bezeichnung, nummer,version) VALUES(228,'nicht gefordert ',0,1);
INSERT INTO motorcycle (id, bezeichnung, nummer,version) VALUES(229,'gefordert ',1,1);
INSERT INTO truck (id, bezeichnung, nummer,version) VALUES(230,'nicht gefordert ',0,1);
INSERT INTO truck (id, bezeichnung, nummer,version) VALUES(231,'gefordert ',1,1);
INSERT INTO omnibus (id, bezeichnung, nummer,version) VALUES(232,'nicht gefordert ',0,1);
INSERT INTO omnibus (id, bezeichnung, nummer,version) VALUES(233,'gefordert ',1,1);
INSERT INTO travel_required (id, bezeichnung, nummer,version) VALUES(234,'nicht erforderlich',1,1);
INSERT INTO travel_required (id, bezeichnung, nummer,version) VALUES(235,'zeitweise',2,1);
INSERT INTO travel_required (id, bezeichnung, nummer,version) VALUES(236,'uneingeschraenkt',3,1);
INSERT INTO handicap (id, bezeichnung, nummer,version) VALUES(237,'nur Schwerbehinderte/Gleichgestellte ',1,1);
INSERT INTO handicap (id, bezeichnung, nummer,version) VALUES(238,'sowohl Schwerbehinderte/Gleichgestellte als auch nicht Schwerbehinderte/Gleichgestellte ',2,1);
