// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.proiectus.data;

import de.proiectus.data.Vokabel;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Vokabel_Roo_Configurable {
    
    declare @type: Vokabel: @Configurable;
    
}
