//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.13 at 09:15:44 PM CET 
//


package de.proiectus.jaxb.error;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.proiectus.jaxb.error package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.proiectus.jaxb.error
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HRBAXMLErrorInformation }
     * 
     */
    public HRBAXMLErrorInformation createHRBAXMLErrorInformation() {
        return new HRBAXMLErrorInformation();
    }

    /**
     * Create an instance of {@link HRBAXMLErrorInformation.ErrorInformation }
     * 
     */
    public HRBAXMLErrorInformation.ErrorInformation createHRBAXMLErrorInformationErrorInformation() {
        return new HRBAXMLErrorInformation.ErrorInformation();
    }

    /**
     * Create an instance of {@link HRBAXMLErrorInformation.ErrorInformation.W3CCompatibility }
     * 
     */
    public HRBAXMLErrorInformation.ErrorInformation.W3CCompatibility createHRBAXMLErrorInformationErrorInformationW3CCompatibility() {
        return new HRBAXMLErrorInformation.ErrorInformation.W3CCompatibility();
    }

    /**
     * Create an instance of {@link HRBAXMLErrorInformation.ErrorInformation.ErrorMessage }
     * 
     */
    public HRBAXMLErrorInformation.ErrorInformation.ErrorMessage createHRBAXMLErrorInformationErrorInformationErrorMessage() {
        return new HRBAXMLErrorInformation.ErrorInformation.ErrorMessage();
    }

}
